### ISSUE TITLE
Type script type definition.

### ISSUE THREAD

**Issue by zenininja** [alexjeffburke/chai-better-shallow-deep-equal#1]
Hi,

Thanks for the plugin. 

Could you please add typescript type definitions so that the plugin can be used with typescript..

**Comment by SQReder** [comment]
bump

**Comment by kamiloski** [comment]
+

**Comment by alexjeffburke** [comment]
Thanks for the interest in the plugin. Can see there is an appetite to use it in projects based around TS, but would like to understand what the desire is a little more before making any decisions about this.

I guess my main question is how would you benefit from this having types.. if one were to encode types for this assertion I think they would basically have to just be `Any` on both sides because it structurally compares any two arbitrary things, and I'm not sure that doing that would gain very much in practice.

Given the above, is providing types still necessary? Or is the problem that you get untyped warnings in project that are configured to be pure TypeScript?

**Comment by kamiloski** [comment]
I use chai-shallow-deep-equal and it works very good, there are added types, I think you can do this the same in this project. This one displays in better way when assertion fail and love it, but I need to have types. So if you can, please add it because its great package!

**Comment by mohan-win** [comment]
@alexjeffburke, Yes, having type definitions would help avoid warnings / errors in a pure type script project. Thanks...

**Comment by alexjeffburke** [comment]
Ok great, thanks for the confirmation :) Attempted to address this with https://github.com/alexjeffburke/chai-better-shallow-deep-equal/commit/1926aef79407caf3737b110bdc3056fbdf6c3040 which has been released as v1.1.0.

**Comment by mohan-win** [comment]
super, thanks..
